sudo: false
language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist --dev

script:
  - vendor/bin/phpcs --standard=PSR1 src/ tests/
  - vendor/bin/phpunit
